### ISSUE TITLE
fail build with python 3.10

### ISSUE THREAD

**Issue by sl1pkn07** [Nekmo/anime-crc#16]
jelow XD

~~~
running bdist_wheel
running build
running build_py
creating build
creating build/lib
creating build/lib/anime_crc
copying anime_crc/management.py -> build/lib/anime_crc
copying anime_crc/crc.py -> build/lib/anime_crc
copying anime_crc/__init__.py -> build/lib/anime_crc
running egg_info
creating anime_crc.egg-info
writing anime_crc.egg-info/PKG-INFO
Traceback (most recent call last):
  File "/tmp/makepkg/crc-git/src/crc/setup.py", line 110, in <module>
    setup(
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 46, in run
    self.build_package_data()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 113, in build_package_data
    for package, src_dir, build_dir, filenames in self.data_files:
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 55, in __getattr__
    self.data_files = self._get_data_files()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 67, in _get_data_files
    self.analyze_manifest()
  File "/usr/lib/python3.10/site-packages/setuptools/command/build_py.py", line 131, in analyze_manifest
    self.run_command('egg_info')
  File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 292, in run
    writer(self, ep.name, os.path.join(self.egg_info, ep.name))
  File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 656, in write_pkg_info
    metadata.write_pkg_info(cmd.egg_info)
  File "/usr/lib/python3.10/distutils/dist.py", line 1117, in write_pkg_info
    self.write_pkg_file(pkg_info)
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 167, in write_pkg_file
    write_field('Summary', single_line(self.get_description()))
  File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 151, in single_line
    raise ValueError('Newlines are not allowed')
ValueError: Newlines are not allowed
~~~

greetings

**Comment by sl1pkn07** [comment]
fixed with:

~~~patch
diff --git a/setup.py b/setup.py
index 4f3c837..305a380 100644
--- a/setup.py
+++ b/setup.py
@@ -13,6 +13,7 @@ EMAIL = 'contacto@nekmo.com'
 URL = 'https://github.com/Nekmo/anime-crc/'
 
 PACKAGE_NAME = 'anime-crc'
+PACKAGE_DESCRIPTION = "Validate and create CRC checksums for files (ex. ``anime video [ABCD01234].mkv``)"
 PACKAGE_DOWNLOAD_URL = 'https://github.com/Nekmo/anime-crc/archive/master.zip'
 MODULE = 'anime_crc'
 REQUIREMENT_FILE = 'requirements.txt'
@@ -114,7 +115,7 @@ setup(
     scripts=scripts,
     include_package_data=True,
 
-    description=__doc__,
+    description=PACKAGE_DESCRIPTION,
     long_description=open(readme, 'r').read(),
     keywords=KEYWORDS,
     download_url=PACKAGE_DOWNLOAD_URL,
~~~

**Comment by Nekmo** [comment]
Fixed! Thanks :)
